In [1]:
import numpy as np
import pandas as pd

In [2]:
# Taking data into pandas dataframe.
data = pd.read_csv("insurance.csv")

In [3]:
data

age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [4]:
# Replacing "sex" column values from string to integer.
data['sex'].replace(to_replace=['male','female'],value=[0,1],inplace=True)

In [5]:
# Replacing "smoker" column values from string to integer.
data['smoker'].replace(to_replace=['no','yes'],value=[0,1],inplace=True)

In [6]:
# Replacing "region" column values from string to integer.
data['region'].replace(to_replace=data['region'].unique(),value=list(range(len(data['region'].unique()))),
                      inplace=True)

In [7]:
data

age  sex   bmi  children  smoker  region  expenses
0      19    1  27.9         0       1       0  16884.92
1      18    0  33.8         1       0       1   1725.55
2      28    0  33.0         3       0       1   4449.46
3      33    0  22.7         0       0       2  21984.47
4      32    0  28.9         0       0       2   3866.86
...   ...  ...   ...       ...     ...     ...       ...
1333   50    0  31.0         3       0       2  10600.55
1334   18    1  31.9         0       0       3   2205.98
1335   18    1  36.9         0       0       1   1629.83
1336   21    1  25.8         0       0       0   2007.95
1337   61    1  29.1         0       1       2  29141.36

[1338 rows x 7 columns]

In [8]:
# Labeling Values of "region" column to One Hot Encoding Vector.
region_variable_ohe = np.eye(len(data['region'].unique()),len(data['region'].unique()))[data['region']] 

In [9]:
region_variable_ohe

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [10]:
processed_data = data.drop(['region'],axis=1)

In [11]:
# Region dataframe after One Hot Vector Encoding.
region_variable_df = pd.DataFrame(data=region_variable_ohe,columns=['Region 0','Region 1','Region 2','Region 3'])

In [12]:
region_variable_df

Region 0  Region 1  Region 2  Region 3
0          1.0       0.0       0.0       0.0
1          0.0       1.0       0.0       0.0
2          0.0       1.0       0.0       0.0
3          0.0       0.0       1.0       0.0
4          0.0       0.0       1.0       0.0
...        ...       ...       ...       ...
1333       0.0       0.0       1.0       0.0
1334       0.0       0.0       0.0       1.0
1335       0.0       1.0       0.0       0.0
1336       1.0       0.0       0.0       0.0
1337       0.0       0.0       1.0       0.0

[1338 rows x 4 columns]

In [13]:
# Joining the processed data and region_variable_df.
processed_data = pd.concat([processed_data,region_variable_df],axis=1)

In [14]:
processed_data

age  sex   bmi  children  smoker  expenses  Region 0  Region 1  \
0      19    1  27.9         0       1  16884.92       1.0       0.0   
1      18    0  33.8         1       0   1725.55       0.0       1.0   
2      28    0  33.0         3       0   4449.46       0.0       1.0   
3      33    0  22.7         0       0  21984.47       0.0       0.0   
4      32    0  28.9         0       0   3866.86       0.0       0.0   
...   ...  ...   ...       ...     ...       ...       ...       ...   
1333   50    0  31.0         3       0  10600.55       0.0       0.0   
1334   18    1  31.9         0       0   2205.98       0.0       0.0   
1335   18    1  36.9         0       0   1629.83       0.0       1.0   
1336   21    1  25.8         0       0   2007.95       1.0       0.0   
1337   61    1  29.1         0       1  29141.36       0.0       0.0   

      Region 2  Region 3  
0          0.0       0.0  
1          0.0       0.0  
2          0.0       0.0  
3          1.0       0.0  
4          1.0       0.0  
...        ...       ...  
1333       1.0       0.0  
1334       0.0       1.0  
1335       0.0       0.0  
1336       0.0       0.0  
1337       1.0       0.0  

[1338 rows x 10 columns]

In [15]:
# Taking labels of training data to a variable labels.
labels = processed_data['expenses']

In [16]:
processed_data.drop(['expenses'],axis=1,inplace=True)

In [17]:
# Adding expense(label) column in the end of dataframe.
processed_data['expenses'] = labels

In [18]:
processed_data

age  sex   bmi  children  smoker  Region 0  Region 1  Region 2  \
0      19    1  27.9         0       1       1.0       0.0       0.0   
1      18    0  33.8         1       0       0.0       1.0       0.0   
2      28    0  33.0         3       0       0.0       1.0       0.0   
3      33    0  22.7         0       0       0.0       0.0       1.0   
4      32    0  28.9         0       0       0.0       0.0       1.0   
...   ...  ...   ...       ...     ...       ...       ...       ...   
1333   50    0  31.0         3       0       0.0       0.0       1.0   
1334   18    1  31.9         0       0       0.0       0.0       0.0   
1335   18    1  36.9         0       0       0.0       1.0       0.0   
1336   21    1  25.8         0       0       1.0       0.0       0.0   
1337   61    1  29.1         0       1       0.0       0.0       1.0   

      Region 3  expenses  
0          0.0  16884.92  
1          0.0   1725.55  
2          0.0   4449.46  
3          0.0  21984.47  
4          0.0   3866.86  
...        ...       ...  
1333       0.0  10600.55  
1334       1.0   2205.98  
1335       0.0   1629.83  
1336       0.0   2007.95  
1337       0.0  29141.36  

[1338 rows x 10 columns]

In [19]:
columns_name = processed_data.columns

In [20]:
# Taking labels of training data to a variable Y.
Y = np.array(processed_data['expenses']).reshape(processed_data.shape[0],1)

In [21]:
X_transpose = np.array(processed_data.drop(['expenses'],axis=1))

In [22]:
Y.shape

(1338, 1)

In [23]:
X_transpose.shape

(1338, 9)

In [24]:
# Normalizing the Data.
X_transpose = (X_transpose - np.mean(X_transpose,axis=0))/np.std(X_transpose,axis=0)

In [25]:
X_transpose_df = pd.DataFrame(data=X_transpose,columns=columns_name[0:9])

In [26]:
X_transpose_df

age       sex       bmi  children    smoker  Region 0  Region 1  \
0    -1.438764  1.010519 -0.453646 -0.908614  1.970587  1.765481 -0.611324   
1    -1.509965 -0.989591  0.514186 -0.078767 -0.507463 -0.566418  1.635795   
2    -0.797954 -0.989591  0.382954  1.580926 -0.507463 -0.566418  1.635795   
3    -0.441948 -0.989591 -1.306650 -0.908614 -0.507463 -0.566418 -0.611324   
4    -0.513149 -0.989591 -0.289606 -0.908614 -0.507463 -0.566418 -0.611324   
...        ...       ...       ...       ...       ...       ...       ...   
1333  0.768473 -0.989591  0.054876  1.580926 -0.507463 -0.566418 -0.611324   
1334 -1.509965  1.010519  0.202511 -0.908614 -0.507463 -0.566418 -0.611324   
1335 -1.509965  1.010519  1.022707 -0.908614 -0.507463 -0.566418  1.635795   
1336 -1.296362  1.010519 -0.798128 -0.908614 -0.507463  1.765481 -0.611324   
1337  1.551686  1.010519 -0.256799 -0.908614  1.970587 -0.566418 -0.611324   

      Region 2  Region 3  
0    -0.566418 -0.565267  
1    -0.566418 -0.565267  
2    -0.566418 -0.565267  
3     1.765481 -0.565267  
4     1.765481 -0.565267  
...        ...       ...  
1333  1.765481 -0.565267  
1334 -0.566418  1.769076  
1335 -0.566418 -0.565267  
1336 -0.566418 -0.565267  
1337  1.765481 -0.565267  

[1338 rows x 9 columns]

In [27]:
# Diving data into training, cross validation and testing data.
training_data = X_transpose[0:int(0.7*X_transpose.shape[0])]
Cv_data = X_transpose[int(0.7*X_transpose.shape[0]):int(0.9*X_transpose.shape[0])]
test_data = X_transpose[int(0.9*X_transpose.shape[0]):]

In [28]:
# Normalizing training labels.
Y_train = (Y[0:int(0.7*X_transpose.shape[0])] - np.mean(Y[0:int(0.7*X_transpose.shape[0])]))/np.std(Y[0:int(0.7*X_transpose.shape[0])])

In [29]:
N_train = training_data.shape[0]
m = training_data.shape[1]

In [30]:
# Function for calculating predicted answers.
def predicted_answer(theta0,theta,X_transpose):
    
    return theta0 + np.matmul(X_transpose,theta)

In [31]:
# Furnction for calculating loss.
def neg_log_loss(labels,predicted_labels,theta,reg_strength):
    
    E = labels - predicted_labels
    
    return (1/labels.shape[0])*(np.matmul(E.T,E)) + (reg_strength*(np.linalg.norm(theta))**2/2) #l2 regularization

# Going to train Linear Regression in mini batch setting

In [32]:
def fit(step_size,reg_strength):
    
    theta0_initial = 0
    theta_initial = np.zeros((m,1))
    epsilon = step_size
    tol = 10**(-6)
    iterations = list()
    neg_log_loss_history = list()
    iteration_number = 0
    mini_batch_size = 72
    time_steps = N_train//mini_batch_size
    epoch_counter = 0
    invalid_value_flag = 0
    
    while(True):
        
        for i in range(0,time_steps):
            
            # Selecting random row indices without replacement.
            rand_indices = np.random.choice(a=np.arange(0,N_train),size=mini_batch_size,replace=False)
            X_transpose_mini_batch = training_data[rand_indices] # Picking data from indices.
            train_labels_mini_batch = Y_train[rand_indices] # Picking lables from indices.
            
            # Initital Predicted Expenses.
            Predicted_answers_initial = predicted_answer(theta0_initial,theta_initial,X_transpose_mini_batch)
            
            theta0_final = theta0_initial + epsilon * np.mean(Predicted_answers_initial-train_labels_mini_batch)
            theta_final = theta_initial + epsilon * ((1/mini_batch_size) * np.matmul(X_transpose_mini_batch.T,
                                                                                    (Predicted_answers_initial-train_labels_mini_batch)) + (reg_strength*theta_initial))
            
            # Mean Squared Error on Initial thetas.
            neg_log_loss_initial = neg_log_loss(train_labels_mini_batch,Predicted_answers_initial,
                                                theta_initial,reg_strength)
            
            # Final Predicted Expenses.
            Predicted_answers_final = predicted_answer(theta0_final,theta_final,X_transpose_mini_batch)
             # Mean Squared Error on Final thetas.
            neg_log_loss_final = neg_log_loss(train_labels_mini_batch,Predicted_answers_final,
                                              theta_final,reg_strength)
            
            # If Nan value is encounter we'll break out of for loop.
            if np.isnan(neg_log_loss_final[0][0]) == True:
                invalid_value_flag = 1
                break
                
            theta0_intial = theta0_final
            theta_initial = theta_final
            
            
            
            iterations.append(iteration_number)
            neg_log_loss_history.append(neg_log_loss_initial[0][0])
            
            iteration_number = iteration_number + 1
            
            #print("Iterations = ", iteration_number,"Mean Squared Error Loss = ", neg_log_loss_initial[0][0])
            
        epoch_counter = epoch_counter + 1
        
        #print("\n\nEpochs = ",epoch_counter,"Mean Squared Loss = ",neg_log_loss_initial[0][0],"\n\n")
        
        
        # If the absolute value of difference between Initially Calculated loss and
        # Final loss is less than tolerence or if we have encountered an Nan value it'll break out of the loop.
        if abs(neg_log_loss_initial - neg_log_loss_final) < tol or invalid_value_flag == 1:
            print("\n\nEpochs = ",epoch_counter,"Mean Squared Loss = ",neg_log_loss_initial[0][0],"\n\n")
            break
        
    return {(step_size,reg_strength):[theta0_final,theta_final]}

In [33]:
# Function for Calculating Mean Squared Error(Without Regularization).
def compute_mse(labels,predicted_labels):
    E = (labels - predicted_labels)
    return (1/labels.shape[0])*np.matmul(E.T,E)

In [34]:
# Function for calculating Root Mean Squared Error.
def rmse(gt_labels,trained_theta0,trained_theta,X_transpose):
    
    predicted_labels = predicted_answer(trained_theta0,trained_theta,X_transpose)
    
    return np.sqrt(compute_mse(gt_labels,predicted_labels))

# Going to use Grid Search

In [35]:
# Performing Grid Search to get minimum rmse for different combinations of step size and regularization hyperparameter.
grid_search_results = list()
for step_size in [0.0000001,0.000001]:
    for reg_hyp_param in [0.0001,0.001,0.01,0.1,1,10,100]:
        grid_search_results.append(fit(step_size,reg_hyp_param))



Epochs =  1 Mean Squared Loss =  1.35347331350606 




Epochs =  1 Mean Squared Loss =  1.0006483594452136 




Epochs =  1 Mean Squared Loss =  0.8453905681390748 




Epochs =  1 Mean Squared Loss =  1.0351376753164283 




Epochs =  1 Mean Squared Loss =  0.9693626122845143 




Epochs =  1 Mean Squared Loss =  0.8717189999730547 




Epochs =  1 Mean Squared Loss =  0.9340176430085538 




Epochs =  5 Mean Squared Loss =  0.7642388208369731 




Epochs =  5 Mean Squared Loss =  0.6322242977903526 




Epochs =  14 Mean Squared Loss =  0.6974806501408899 




Epochs =  1 Mean Squared Loss =  0.6339486926607532 




Epochs =  4 Mean Squared Loss =  0.6288884009926214 




Epochs =  14 Mean Squared Loss =  0.7276693466136088 




Epochs =  7 Mean Squared Loss =  0.7162806199094766 




In [36]:
grid_search_results

[{(1e-07, 0.0001): [-1.3194394148886062e-08,
   array([[-4.20660338e-07],
          [ 8.29893771e-08],
          [-2.77641886e-07],
          [-6.47792992e-08],
          [-1.04299275e-06],
          [ 6.65929137e-08],
          [-1.48677291e-07],
          [ 9.64682573e-08],
          [-8.78369617e-09]])]},
 {(1e-07, 0.001): [-8.33439921487822e-09,
   array([[-4.34692378e-07],
          [-4.58624070e-08],
          [-1.87554199e-07],
          [-1.16403542e-07],
          [-1.01995608e-06],
          [ 3.48261244e-08],
          [-1.30433667e-08],
          [ 1.41478667e-08],
          [-3.54756581e-08]])]},
 {(1e-07, 0.01): [1.4027607815358523e-08,
   array([[-4.28932638e-07],
          [ 4.82615474e-08],
          [-2.27790811e-07],
          [-4.75912730e-08],
          [-9.31018160e-07],
          [ 5.46806938e-08],
          [-9.70875795e-08],
          [ 8.03049944e-08],
          [-3.42710144e-08]])]},
 {(1e-07, 0.1): [-3.0492750824831024e-09,
   array([[-3.73335603e-07],
     

In [37]:
# Saving RMSE results for training data calulated on different stepsize and
# regularization hyperparmeter in grid_search_train_results.
grid_search_train_results = dict()

for configs in grid_search_results:
    
    trained_params = list(configs.values())
    grid_search_train_results[tuple(configs.keys())] = rmse(Y_train,trained_params[0][0],
                                                            trained_params[0][1],training_data)

In [38]:
grid_search_train_results

{((1e-07, 0.0001),): array([[1.00000103]]),
 ((1e-07, 0.001),): array([[1.00000098]]),
 ((1e-07, 0.01),): array([[1.00000093]]),
 ((1e-07, 0.1),): array([[1.0000009]]),
 ((1e-07, 1),): array([[1.00000102]]),
 ((1e-07, 10),): array([[1.00000094]]),
 ((1e-07, 100),): array([[1.00000105]]),
 ((1e-06, 0.0001),): array([[1.00004924]]),
 ((1e-06, 0.001),): array([[1.00005101]]),
 ((1e-06, 0.01),): array([[1.00014155]]),
 ((1e-06, 0.1),): array([[1.00001044]]),
 ((1e-06, 1),): array([[1.00004034]]),
 ((1e-06, 10),): array([[1.0001405]]),
 ((1e-06, 100),): array([[1.00006809]])}

In [39]:
# Finding Minimum RMSE
minimum_grid_train = min(grid_search_train_results.values())

In [40]:
# Finding Best Step Size and Regularization Hyperparameter for we whcih we got minimum RMSE.
rmse_sandr_grid_train = (list(grid_search_train_results.keys())[list(grid_search_train_results.values()).index(minimum_grid_train)]) 

In [41]:
print("The best Step Size and Regularization Hyper Paramter in grid search is ", rmse_sandr_grid_train[0][0],"and",
      rmse_sandr_grid_train[0][1]," with minimum rmse ",minimum_grid_train[0][0],"on Training Data.")

The best Step Size and Regularization Hyper Paramter in grid search is  1e-07 and 0.1  with minimum rmse  1.000000896154505 on Training Data.


In [42]:
# Normalizing Cross Validation labels.
Y_cv = (Y[int(0.7*X_transpose.shape[0]):int(0.9*X_transpose.shape[0])] - np.mean(Y[int(0.7*X_transpose.shape[0]):int(0.9*X_transpose.shape[0])]))/np.std(Y[int(0.7*X_transpose.shape[0]):int(0.9*X_transpose.shape[0])])

In [43]:
# Saving RMSE results for cross validation data calulated on different stepsize and
# regularization hyperparmeter in grid_search_train_results.
grid_search_cv_results = dict()

for configs in grid_search_results:
    
    trained_params = list(configs.values())
    grid_search_cv_results[tuple(configs.keys())] = rmse(Y_cv,trained_params[0][0],
                                                         trained_params[0][1],Cv_data)

In [44]:
grid_search_cv_results

{((1e-07, 0.0001),): array([[1.00000101]]),
 ((1e-07, 0.001),): array([[1.00000093]]),
 ((1e-07, 0.01),): array([[1.00000089]]),
 ((1e-07, 0.1),): array([[1.00000086]]),
 ((1e-07, 1),): array([[1.00000098]]),
 ((1e-07, 10),): array([[1.00000091]]),
 ((1e-07, 100),): array([[1.00000101]]),
 ((1e-06, 0.0001),): array([[1.00004738]]),
 ((1e-06, 0.001),): array([[1.0000489]]),
 ((1e-06, 0.01),): array([[1.00013649]]),
 ((1e-06, 0.1),): array([[1.00001014]]),
 ((1e-06, 1),): array([[1.00003902]]),
 ((1e-06, 10),): array([[1.00013515]]),
 ((1e-06, 100),): array([[1.00006517]])}

In [45]:
# Finding Minimum RMSE
minimum_grid_cv = min(grid_search_cv_results.values())

In [46]:
# Finding Best Step Size and Regularization Hyperparameter for we whcih we got minimum RMSE.
rmse_sandr_grid_cv = (list(grid_search_cv_results.keys())[list(grid_search_cv_results.values()).index(minimum_grid_cv)]) 

In [47]:
print("The best Step Size and Regularization Hyper Paramter in grid search is ", rmse_sandr_grid_cv[0][0],"and",
      rmse_sandr_grid_cv[0][1]," with minimum rmse ",minimum_grid_cv[0][0],"on Cross Validation Data.")

The best Step Size and Regularization Hyper Paramter in grid search is  1e-07 and 0.1  with minimum rmse  1.0000008595813137 on Cross Validation Data.


In [48]:
# Normalizing Testing labels.
Y_test = (Y[int(0.9*X_transpose.shape[0]):] - np.mean(Y[int(0.9*X_transpose.shape[0]):]))/np.std(Y[int(0.9*X_transpose.shape[0]):])

In [49]:
# Saving RMSE results for test data calulated on different stepsize and
# regularization hyperparmeter in grid_search_train_results.
grid_search_test_results = dict()

for configs in grid_search_results:
    
    trained_params = list(configs.values())
    grid_search_test_results[tuple(configs.keys())] = rmse(Y_test,trained_params[0][0],
                                                           trained_params[0][1],test_data)

In [50]:
grid_search_test_results

{((1e-07, 0.0001),): array([[1.0000011]]),
 ((1e-07, 0.001),): array([[1.00000105]]),
 ((1e-07, 0.01),): array([[1.00000099]]),
 ((1e-07, 0.1),): array([[1.00000099]]),
 ((1e-07, 1),): array([[1.00000112]]),
 ((1e-07, 10),): array([[1.00000102]]),
 ((1e-07, 100),): array([[1.00000112]]),
 ((1e-06, 0.0001),): array([[1.00005271]]),
 ((1e-06, 0.001),): array([[1.00005463]]),
 ((1e-06, 0.01),): array([[1.00015208]]),
 ((1e-06, 0.1),): array([[1.00001133]]),
 ((1e-06, 1),): array([[1.00004287]]),
 ((1e-06, 10),): array([[1.00015053]]),
 ((1e-06, 100),): array([[1.00007299]])}

In [51]:
# Finding Minimum RMSE
minimum_grid_test = min(grid_search_test_results.values())

In [52]:
# Finding Best Step Size and Regularization Hyperparameter for we whcih we got minimum RMSE.
rmse_sandr_grid_test = (list(grid_search_test_results.keys())[list(grid_search_test_results.values()).index(minimum_grid_test)])

In [53]:
print("The best Step Size and Regularization Hyper Paramter in grid search is ", rmse_sandr_grid_test[0][0],"and",
      rmse_sandr_grid_test[0][1]," with minimum rmse ",minimum_grid_test[0][0],"on Testing Data.")

The best Step Size and Regularization Hyper Paramter in grid search is  1e-07 and 0.1  with minimum rmse  1.0000009855174 on Testing Data.


# Going to use Random Search

In [54]:
random_search_results = list()

# Randomly searching 10 best step size and regularization hyperparameter from using unifrom distribution for minimum rmse .
for i in range(10):
    
    step_size = np.random.uniform(low=10**(-7),high=10**(-6))# probability of occuring the values between lower limit and upper limit is equal.
    reg_hyp_param = np.random.uniform(low=10**(-4),high=10**(3))
    random_search_results.append(fit(step_size,reg_hyp_param))



Epochs =  2 Mean Squared Loss =  0.8120153794581839 




Epochs =  2 Mean Squared Loss =  1.0971301641208688 




Epochs =  1 Mean Squared Loss =  0.940643823759778 




Epochs =  1 Mean Squared Loss =  0.9798803077969216 




Epochs =  1 Mean Squared Loss =  0.644877010534635 




Epochs =  1 Mean Squared Loss =  1.1126566547568257 




Epochs =  1 Mean Squared Loss =  1.175864435956915 




Epochs =  1 Mean Squared Loss =  0.7773222493532271 




Epochs =  1 Mean Squared Loss =  0.924900239072884 




Epochs =  1 Mean Squared Loss =  0.8364547818712147 




In [55]:
random_search_results

[{(6.472039134179764e-07, 375.13282533827834): [-1.4757139015571047e-08,
   array([[-5.17037260e-06],
          [ 2.12307664e-07],
          [-3.64432854e-06],
          [-1.19274898e-06],
          [-1.26103416e-05],
          [ 1.55732477e-06],
          [-6.89846545e-07],
          [ 3.10747335e-07],
          [-1.15340620e-06]])]},
 {(3.509884847497786e-07, 918.2528410451323): [-2.458028065692077e-08,
   array([[-2.68094132e-06],
          [ 2.02031469e-07],
          [-1.79206582e-06],
          [-5.98644866e-07],
          [-7.05638052e-06],
          [ 7.22398536e-07],
          [-7.54648719e-07],
          [ 2.32618096e-07],
          [-1.72076262e-07]])]},
 {(5.561720987931346e-07, 810.9380424539869): [3.600781511329122e-08,
   array([[-2.04963064e-06],
          [ 2.80639485e-07],
          [-1.25000802e-06],
          [-3.05283090e-07],
          [-5.51382976e-06],
          [ 3.83462640e-07],
          [-7.47960237e-07],
          [ 4.79700106e-07],
          [-8.70742123e-

In [56]:
# Saving RMSE results for training data calulated on different stepsize and
# regularization hyperparmeter in random_search_train_results.

random_search_train_results = dict()

for configs in random_search_results:
    
    trained_params = list(configs.values())
    random_search_train_results[tuple(configs.keys())] = rmse(Y_train,trained_params[0][0],
                                                              trained_params[0][1],training_data)

In [57]:
random_search_train_results

{((6.472039134179764e-07, 375.13282533827834),): array([[1.00001245]]),
 ((3.509884847497786e-07, 918.2528410451323),): array([[1.00000685]]),
 ((5.561720987931346e-07, 810.9380424539869),): array([[1.00000532]]),
 ((4.489013078205559e-07, 727.2789304076855),): array([[1.00000436]]),
 ((7.694488255322975e-07, 490.67850470201523),): array([[1.00000779]]),
 ((1.1685509748724358e-07, 147.40540087053483),): array([[1.00000118]]),
 ((2.574747213615065e-07, 354.7562219747649),): array([[1.00000237]]),
 ((4.35208154504429e-07, 61.115148235337735),): array([[1.00000457]]),
 ((2.681209752211968e-07, 476.00342801667074),): array([[1.00000277]]),
 ((4.0350870742710293e-07, 458.1714230252515),): array([[1.00000402]])}

In [58]:
# Finding Minimum RMSE
minimum_random_train = min(random_search_train_results.values())

In [59]:
# Finding Best Step Size and Regularization Hyperparameter for we whcih we got minimum RMSE.
rmse_sandr_train = (list(random_search_train_results.keys())[list(random_search_train_results.values()).index(minimum_random_train)]) 

In [60]:
print("The best Step Size and Regularization Hyper Paramter in random search is ", rmse_sandr_train[0][0],"and",
      rmse_sandr_train[0][1]," with minimum rmse ",minimum_random_train[0][0], "on Training Data.")

The best Step Size and Regularization Hyper Paramter in random search is  1.1685509748724358e-07 and 147.40540087053483  with minimum rmse  1.000001180418912 on Training Data.


In [61]:
# Saving RMSE results for Cross Validation data calulated on different stepsize and
# regularization hyperparmeter in random_search_cv_results.

random_search_cv_results = dict()

for configs in random_search_results:
    
    trained_params = list(configs.values())
    random_search_cv_results[tuple(configs.keys())] = rmse(Y_cv,trained_params[0][0],
                                                              trained_params[0][1],Cv_data)

In [62]:
random_search_cv_results

{((6.472039134179764e-07, 375.13282533827834),): array([[1.00001198]]),
 ((3.509884847497786e-07, 918.2528410451323),): array([[1.00000669]]),
 ((5.561720987931346e-07, 810.9380424539869),): array([[1.00000521]]),
 ((4.489013078205559e-07, 727.2789304076855),): array([[1.00000428]]),
 ((7.694488255322975e-07, 490.67850470201523),): array([[1.00000735]]),
 ((1.1685509748724358e-07, 147.40540087053483),): array([[1.00000113]]),
 ((2.574747213615065e-07, 354.7562219747649),): array([[1.00000229]]),
 ((4.35208154504429e-07, 61.115148235337735),): array([[1.00000435]]),
 ((2.681209752211968e-07, 476.00342801667074),): array([[1.00000263]]),
 ((4.0350870742710293e-07, 458.1714230252515),): array([[1.000004]])}

In [63]:
# Finding Minimum RMSE
minimum_random_cv = min(random_search_cv_results.values())

In [64]:
# Finding Best Step Size and Regularization Hyperparameter for we whcih we got minimum RMSE.
rmse_sandr_cv = (list(random_search_cv_results.keys())[list(random_search_cv_results.values()).index(minimum_random_cv)]) 

In [65]:
print("The best Step Size and Regularization Hyper Paramter in random search is ", rmse_sandr_cv[0][0],"and",
      rmse_sandr_cv[0][1]," with minimum rmse ",minimum_random_cv[0][0], "on Cross Validation Data.")

The best Step Size and Regularization Hyper Paramter in random search is  1.1685509748724358e-07 and 147.40540087053483  with minimum rmse  1.0000011264295217 on Cross Validation Data.


In [66]:
# Saving RMSE results for Test data calulated on different stepsize and
# regularization hyperparmeter in random_search_test_results.

random_search_test_results = dict()

for configs in random_search_results:
    
    trained_params = list(configs.values())
    random_search_test_results[tuple(configs.keys())] = rmse(Y_test,trained_params[0][0],
                                                             trained_params[0][1],test_data)

In [67]:
# Finding Minimum RMSE
minimum_random_test = min(random_search_test_results.values())

In [68]:
# Finding Best Step Size and Regularization Hyperparameter for we whcih we got minimum RMSE.
rmse_sandr_test = (list(random_search_test_results.keys())[list(random_search_test_results.values()).index(minimum_random_test)]) 

In [69]:
print("The best Step Size and Regularization Hyper Paramter in random search is ", rmse_sandr_test[0][0],"and",
      rmse_sandr_test[0][1]," with minimum rmse ",minimum_random_test[0][0], "on Testing Data.")

The best Step Size and Regularization Hyper Paramter in random search is  1.1685509748724358e-07 and 147.40540087053483  with minimum rmse  1.000001272271289 on Testing Data.
